version: '3'

volumes:
  postgres_data: {}

networks:
  acuero_net:

services:
  postgres:
    image: acuero/n5now_challenge-django:latest
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    # networks:
    #   - acuero_net

  django:
    image: acuero/n5now_challenge-django:latest
    container_name: django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    command: /app/start
    # networks:
    #   - acuero_net
