version: '3'

volumes:
  postgres_data: {}

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    command: sh -c "python /usr/src/app/manage.py runserver 0.0.0.0:8000"
  postgres:
    image: postgres:14
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
