version: '3'

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  django:
    container_name: django
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    command:
      - sh -c "python /app/manage.py runserver 0.0.0.0:8000"
