# Generated by Django 4.1.13 on 2024-04-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracion',
            options={'verbose_name': 'Configuración', 'verbose_name_plural': 'Configuración'},
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='name',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='nombre',
            field=models.CharField(default='CONFIGURACION GENERAL', help_text='Configuración General.', max_length=90, verbose_name='Configuracion'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='dias_antiguedad_infraccion',
            field=models.PositiveIntegerField(default=90, help_text='Una infracción se considera válida si su antiguedad en días es menor o igual a este valor.', verbose_name='Antiguedad válida de una infraccion (dias)'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Campo abierto para alguna descripcion u observaciones del objeto', max_length=255, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Campo abierto para alguna descripcion u observaciones del objeto', max_length=255, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Campo abierto para alguna descripcion u observaciones del objeto', max_length=255, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='oficial',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Campo abierto para alguna descripcion u observaciones del objeto', max_length=255, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Campo abierto para alguna descripcion u observaciones del objeto', max_length=255, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Campo abierto para alguna descripcion u observaciones del objeto', max_length=255, verbose_name='Observaciones'),
        ),
    ]
