# Generated by Django 4.1.13 on 2024-04-28 06:49

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_infraccion_options_alter_oficial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='oficial',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='oficial',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='oficial',
            name='email',
        ),
        migrations.RemoveField(
            model_name='oficial',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='oficial',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='oficial',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='oficial',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='oficial',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='oficial',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='oficial',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='oficial',
            name='password',
        ),
        migrations.RemoveField(
            model_name='oficial',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='oficial',
            name='username',
        ),
        migrations.AddField(
            model_name='oficial',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='fecha_infraccion',
            field=models.DateTimeField(help_text='Fecha de la infracción', validators=[core.validators.validate_fecha_infraccion], verbose_name='Fecha de la infracción'),
        ),
    ]
